---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: attendee-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - create
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - infinispan.org
    resources:
      - caches
      - infinispans
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  
  