INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Apricot', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Avocado', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Banana', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Bilberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Blackberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Blackcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Blueberry', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Boysenberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Currant', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cherry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cherimoya', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Chico fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cloudberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Coconut', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cranberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cucumber', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Custard apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Damson', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Date', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Dragonfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Durian', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Elderberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Feijoa', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Fig', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Goji berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Gooseberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Grape', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Raisin', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Grapefruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Guava', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Honeyberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Huckleberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Jabuticaba', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Jackfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Jambul', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Jujube', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Juniper berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Kiwano', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Kiwifruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Kumquat', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Lemon', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Lime', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Loquat', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Longan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Lychee', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Mango', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Marionberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Melon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Cantaloupe', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Honeydew', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Watermelon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Miracle fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Mulberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Nectarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Nance', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Olive', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Orange', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Blood orange', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Clementine', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Mandarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Tangerine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Papaya', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Passionfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Peach', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Pear', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Persimmon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Physalis', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Plantain', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Plum', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Prune', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Pineapple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Plumcot', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Pomegranate', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Pomelo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Purple mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Quince', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Raspberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Salmonberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Rambutan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Redcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Salal berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Salak', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Satsuma', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Soursop', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Star fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Solanum quitoense', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Strawberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Tamarillo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Tamarind', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Ugli fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( FRUIT_SEQ.NEXTVAL, 'Yuzu', 'All');