INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Apricot', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Avocado', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Banana', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Bilberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Blackberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Blackcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Blueberry', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Boysenberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Currant', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cherry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cherimoya', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Chico fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cloudberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Coconut', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cranberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cucumber', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Custard apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Damson', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Date', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Dragonfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Durian', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Elderberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Feijoa', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Fig', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Goji berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Gooseberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Grape', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Raisin', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Grapefruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Guava', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Honeyberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Huckleberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Jabuticaba', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Jackfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Jambul', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Jujube', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Juniper berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Kiwano', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Kiwifruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Kumquat', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Lemon', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Lime', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Loquat', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Longan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Lychee', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Mango', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Marionberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Melon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Cantaloupe', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Honeydew', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Watermelon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Miracle fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Mulberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Nectarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Nance', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Olive', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Orange', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Blood orange', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Clementine', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Mandarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Tangerine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Papaya', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Passionfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Peach', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Pear', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Persimmon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Physalis', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Plantain', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Plum', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Prune', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Pineapple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Plumcot', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Pomegranate', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Pomelo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Purple mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Quince', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Raspberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Salmonberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Rambutan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Redcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Salal berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Salak', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Satsuma', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Soursop', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Star fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Solanum quitoense', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Strawberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Tamarillo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Tamarind', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Ugli fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('FRUIT_SEQ'), 'Yuzu', 'All');
