apiVersion: v1
kind: Secret
metadata:
  name: backend-database-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_HOST: backend-database
  DB_NAME: FRUITSDB
  DB_PASSWORD: secret
  DB_USER: luke

