INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Apricot', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Avocado', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Banana', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Bilberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Blackberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Blackcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Blueberry', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Boysenberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Currant', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cherry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cherimoya', 'Fall');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Chico fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cloudberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Coconut', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cranberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cucumber', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Custard apple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Damson', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Date', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Dragonfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Durian', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Elderberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Feijoa', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Fig', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Goji berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Gooseberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Grape', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Raisin', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Grapefruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Guava', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Honeyberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Huckleberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Jabuticaba', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Jackfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Jambul', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Jujube', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Juniper berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Kiwano', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Kiwifruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Kumquat', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Lemon', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Lime', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Loquat', 'Summer');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Longan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Lychee', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Mango', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Marionberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Melon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Cantaloupe', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Honeydew', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Watermelon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Miracle fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Mulberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Nectarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Nance', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Olive', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Orange', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Blood orange', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Clementine', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Mandarine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Tangerine', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Papaya', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Passionfruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Peach', 'Winter');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Pear', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Persimmon', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Physalis', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Plantain', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Plum', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Prune', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Pineapple', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Plumcot', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Pomegranate', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Pomelo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Purple mangosteen', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Quince', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Raspberry', 'All');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Salmonberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Rambutan', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Redcurrant', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Salal berry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Salak', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Satsuma', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Soursop', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Star fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Solanum quitoense', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Strawberry', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Tamarillo', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Tamarind', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Ugli fruit', 'Spring');
INSERT INTO Fruit(id,name,season) VALUES ( nextval ('hibernate_sequence') , 'Yuzu', 'All');