apiVersion: infinispan.org/v2alpha1
kind: Cache
metadata:
  name: eda-infinispan-alerts
  namespace: {{ .Values.namespace }}
spec:
  adminAuth: 
    secretName: eda-infinispan-caches-credentials
  clusterName: eda-infinispan
  name: alerts
  template: >-
    <infinispan>
      <cache-container>
        <replicated-cache name="alerts" mode="SYNC" statistics="true">
          <memory>                          
            <binary eviction="MEMORY" size="419430400"/> <!-- 400 MB -->
          </memory>
          <expiration lifespan="7200000"/> <!-- 2 hours -->
        </replicated-cache>
      </cache-container>
    </infinispan>
